export const OBJECT_TYPE = {
  0: 'UNKNOWN',
  1: 'FILE',
  2: 'PROCESS',
  3: 'MODULE',
  4: 'SERVICE',
  5: 'UPN',
  6: 'IP',
  7: 'DNS',
  8: 'SIGNATURE',
  9: 'WINNET',
  10: 'FILE_PROPAGATION',
  11: 'INJECT_API',
  12: 'URL_MON',
  13: 'INTERNET',
  14: 'REGISTRY',
  15: 'AUTORUN_PROCESS',
  16: 'MUTEX',
  17: 'SEMAPHORE'
}

let META_UNKNOWN = 0;
let META_TYPE = 0 + 1;
let META_ACTIVITY = 0 + 2;
let META_FIRST_SIGHT = 0 + 3;
let META_MATCHING_TYPE = 0 + 4;
let META_MATCHING_VALUE = 0 + 5;
let META_RATING = 100 + 0;
let META_FILE_SHA1 = 100 + 1;
let META_FILE_MD5 = 100 + 2;
let META_USER = 100 + 3;
let META_PATH = 100 + 4;
let META_FILE_NAME = 100 + 5;
let META_FILE_CREATION = 100 + 6;
let META_SIGNER = 100 + 7;
let META_PROCESS_PID = 100 + 8;
let META_PROCESS_CMD = 100 + 9;
let META_FILE_MODIFICATON = 100 + 10;
let META_FILE_ACCESS = 100 + 11;
let META_FILE_SIZE = 100 + 12;
let META_SRC_PATH = 100 + 13;
let META_SRC_FILENAME = 100 + 14;
let META_DST_PATH = 100 + 15;
let META_DST_FILENAME = 100 + 16;
let META_FULLPATH = 100 + 17;
let META_SERVICE_NAME = 200 + 0;
let META_SERVICE_DESCRIPTION = 200 + 1;
let META_SERVICE_DISPLAYNAME = 200 + 2;
let META_DIRECTORY_HANDLE = 200 + 3;
let META_FILE_HANDLE = 200 + 4;
let META_KEY_HANDLE = 200 + 5;
let META_WINDOWSTATION_HANDLE = 200 + 6;
let META_DESKTOP_HANDLE = 200 + 7;
let META_MUTANT_HANDLE = 200 + 8;
let META_SECTION_HANDLE = 200 + 9;
let META_EVENT_HANDLE = 200 + 10;
let META_ALPC_PORT_HANDLE = 200 + 11;
let META_JOB_HANDLE = 200 + 12;
let META_TIMER_HANDLE = 200 + 13;
let META_SYMBOLICLINK_HANDLE = 200 + 14;
let META_SESSION_HANDLE = 200 + 15;
let META_SEMAPHORE_HANDLE = 200 + 16;
let META_DLL = 200 + 17;
let META_USER_USER_NAME = 300 + 0;
let META_USER_OPERATION_INUSE = 300 + 1;
let META_IP_PORT = 400 + 0;
let META_IP_STATE = 400 + 1;
let META_IP_IP = 400 + 2;
let META_IP_SRC = 400 + 3;
let META_IP_DST = 400 + 4;
let META_DOMAIN_DOMAIN = 500 + 0;
let META_DOMAIN_IP = 500 + 1;
let META_SIGNATURE_SIGNATURE = 600 + 0;
let META_WINNET_LAUNCH_CMD = 700 + 0;
let META_FILE_PROPAGATION_SRC_FILENAME = 800 + 0;
let META_INJECT_TARGET_PROCESSNAME = 900 + 0;
let META_INJECT_TARGET_PID = 900 + 1;
let META_INJECT_TARGET_TID = 900 + 2;
let META_INJECT_START_ADDRESS = 900 + 3;
let META_INJECT_SIZE_OF_WRITE = 900 + 4;
let META_INJECT_HOOK_ID = 900 + 5;
let META_INJECT_OPERATION_STR = 900 + 6;
let META_INJECT_FILE_STR = 900 + 7;
let META_INJECT_PARAM_STR = 900 + 8;
let META_INJECT_DICT_STR = 900 + 9;
let META_INJECT_SHOW_COMMAND = 900 + 10;
let META_INJECT_ATTRIBUTES = 900 + 11;
let META_INJECT_PRIVILEGE_NAME = 900 + 12;
let META_URLMON_URL = 1000 + 0;
let META_URLMON_FILENAME = 1000 + 1;
let META_INTERNET_PROXY_NAME = 1100 + 0;
let META_INTERNET_HOST_NAME = 1100 + 1;
let META_INTERNET_URL = 1100 + 2;
let META_INTERNET_PORT = 1100 + 3;
let META_REGISTRY_ROOT = 1200 + 0;
let META_REGISTRY_KEY_HANDLE = 1200 + 1;
let META_REGISTRY_VALUE = 1200 + 2;
let META_REGISTRY_DATA = 1200 + 3;
let META_REGISTRY_KEY = 1200 + 4;
let META_MUTEX_MUTEX = 1300 + 0;
let META_SEMAPHORE_SEMAPHORE = 1400 + 0;

export const META = {
  [META_UNKNOWN]: 'META_UNKNOWN',
  [META_TYPE]: 'META_TYPE',
  [META_ACTIVITY]: 'META_ACTIVITY',
  [META_FIRST_SIGHT]: 'META_FIRST_SIGHT',
  [META_MATCHING_TYPE]: 'META_MATCHING_TYPE',
  [META_MATCHING_VALUE]: 'META_MATCHING_VALUE',
  [META_RATING]: 'META_RATING',
  [META_FILE_SHA1]: 'META_FILE_SHA1',
  [META_FILE_MD5]: 'META_FILE_MD5',
  [META_USER]: 'META_USER',
  [META_PATH]: 'META_PATH',
  [META_FILE_NAME]: 'META_FILE_NAME',
  [META_FILE_CREATION]: 'META_FILE_CREATION',
  [META_SIGNER]: 'META_SIGNER',
  [META_PROCESS_PID]: 'META_PROCESS_PID',
  [META_PROCESS_CMD]: 'META_PROCESS_CMD',
  [META_FILE_MODIFICATON]: 'META_FILE_MODIFICATON',
  [META_FILE_ACCESS]: 'META_FILE_ACCESS',
  [META_FILE_SIZE]: 'META_FILE_SIZE',
  [META_SRC_PATH]: 'META_SRC_PATH',
  [META_SRC_FILENAME]: 'META_SRC_FILENAME',
  [META_DST_PATH]: 'META_DST_PATH',
  [META_DST_FILENAME]: 'META_DST_FILENAME',
  [META_FULLPATH]: 'META_FULLPATH',
  [META_SERVICE_NAME]: 'META_SERVICE_NAME',
  [META_SERVICE_DESCRIPTION]: 'META_SERVICE_DESCRIPTION',
  [META_SERVICE_DISPLAYNAME]: 'META_SERVICE_DISPLAYNAME',
  [META_DIRECTORY_HANDLE]: 'META_DIRECTORY_HANDLE',
  [META_FILE_HANDLE]: 'META_FILE_HANDLE',
  [META_KEY_HANDLE]: 'META_KEY_HANDLE',
  [META_WINDOWSTATION_HANDLE]: 'META_WINDOWSTATION_HANDLE',
  [META_DESKTOP_HANDLE]: 'META_DESKTOP_HANDLE',
  [META_MUTANT_HANDLE]: 'META_MUTANT_HANDLE',
  [META_SECTION_HANDLE]: 'META_SECTION_HANDLE',
  [META_EVENT_HANDLE]: 'META_EVENT_HANDLE',
  [META_ALPC_PORT_HANDLE]: 'META_ALPC_PORT_HANDLE',
  [META_JOB_HANDLE]: 'META_JOB_HANDLE',
  [META_TIMER_HANDLE]: 'META_TIMER_HANDLE',
  [META_SYMBOLICLINK_HANDLE]: 'META_SYMBOLICLINK_HANDLE',
  [META_SESSION_HANDLE]: 'META_SESSION_HANDLE',
  [META_SEMAPHORE_HANDLE]: 'META_SEMAPHORE_HANDLE',
  [META_DLL]: 'META_DLL',
  [META_USER_USER_NAME]: 'META_USER_USER_NAME',
  [META_USER_OPERATION_INUSE]: 'META_USER_OPERATION_INUSE',
  [META_IP_PORT]: 'META_IP_PORT',
  [META_IP_STATE]: 'META_IP_STATE',
  [META_IP_IP]: 'META_IP_IP',
  [META_IP_SRC]: 'META_IP_SRC',
  [META_IP_DST]: 'META_IP_DST',
  [META_DOMAIN_DOMAIN]: 'META_DOMAIN_DOMAIN',
  [META_DOMAIN_IP]: 'META_DOMAIN_IP',
  [META_SIGNATURE_SIGNATURE]: 'META_SIGNATURE_SIGNATURE',
  [META_WINNET_LAUNCH_CMD]: 'META_WINNET_LAUNCH_CMD',
  [META_FILE_PROPAGATION_SRC_FILENAME]: 'META_FILE_PROPAGATION_SRC_FILENAME',
  [META_INJECT_TARGET_PROCESSNAME]: 'META_INJECT_TARGET_PROCESSNAME',
  [META_INJECT_TARGET_PID]: 'META_INJECT_TARGET_PID',
  [META_INJECT_TARGET_TID]: 'META_INJECT_TARGET_TID',
  [META_INJECT_START_ADDRESS]: 'META_INJECT_START_ADDRESS',
  [META_INJECT_SIZE_OF_WRITE]: 'META_INJECT_SIZE_OF_WRITE',
  [META_INJECT_HOOK_ID]: 'META_INJECT_HOOK_ID',
  [META_INJECT_OPERATION_STR]: 'META_INJECT_OPERATION_STR',
  [META_INJECT_FILE_STR]: 'META_INJECT_FILE_STR',
  [META_INJECT_PARAM_STR]: 'META_INJECT_PARAM_STR',
  [META_INJECT_DICT_STR]: 'META_INJECT_DICT_STR',
  [META_INJECT_SHOW_COMMAND]: 'META_INJECT_SHOW_COMMAND',
  [META_INJECT_ATTRIBUTES]: 'META_INJECT_ATTRIBUTES',
  [META_INJECT_PRIVILEGE_NAME]: 'META_INJECT_PRIVILEGE_NAME',
  [META_URLMON_URL]: 'META_URLMON_URL',
  [META_URLMON_FILENAME]: 'META_URLMON_FILENAME',
  [META_INTERNET_PROXY_NAME]: 'META_INTERNET_PROXY_NAME',
  [META_INTERNET_HOST_NAME]: 'META_INTERNET_HOST_NAME',
  [META_INTERNET_URL]: 'META_INTERNET_URL',
  [META_INTERNET_PORT]: 'META_INTERNET_PORT',
  [META_REGISTRY_ROOT]: 'META_REGISTRY_ROOT',
  [META_REGISTRY_KEY_HANDLE]: 'META_REGISTRY_KEY_HANDLE',
  [META_REGISTRY_VALUE]: 'META_REGISTRY_VALUE',
  [META_REGISTRY_DATA]: 'META_REGISTRY_DATA',
  [META_REGISTRY_KEY]: 'META_REGISTRY_KEY',
  [META_MUTEX_MUTEX]: 'META_MUTEX_MUTEX',
  [META_SEMAPHORE_SEMAPHORE]: 'META_SEMAPHORE_SEMAPHORE'
}
export const OPERATION = {
  0: 'UNKNOWN',
  1: 'CREATION',
  2: 'INJECT',
  3: 'MODIFY',
  4: 'DELETE',
  5: 'COPY',
  6: 'MOVE',
  7: 'QUERY',
  8: 'ACCESS',
  9: 'IMPERSONATE',
  10: 'CHANGEPASSWORD',
  11: 'QUERYUSERINFO',
  12: 'CHANGEGROUP',
  13: 'INUSE',
  14: 'SIGNATURE',
  15: 'WINNET',
  16: 'FILE_PROPAGATION',
  17: 'URLDOWNLODFILE',
  18: 'INTERNET',
  19: 'CONNECT',
  20: 'EXTRACT',
  21: 'LOAD',
  22: 'CREATETHREAD'
}